// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRexyMCRZAHfqoHWlOrYUtQUzmwKAhQ0I',
    appId: '1:987228422764:web:12145cca53bdf34a90ce49',
    messagingSenderId: '987228422764',
    projectId: 'expense-tracker-app-bb95a',
    authDomain: 'expense-tracker-app-bb95a.firebaseapp.com',
    storageBucket: 'expense-tracker-app-bb95a.firebasestorage.app',
    measurementId: 'G-HLTXVVCQDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcnJ6dl90B_3KwIg8DcBIkaDz5aE5tyFs',
    appId: '1:987228422764:android:cabdb2e6e5a7011f90ce49',
    messagingSenderId: '987228422764',
    projectId: 'expense-tracker-app-bb95a',
    storageBucket: 'expense-tracker-app-bb95a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwgiVTxuXOSoKjiqHsTGTJwkesmpiNaVI',
    appId: '1:987228422764:ios:7322c3ba45bad6c890ce49',
    messagingSenderId: '987228422764',
    projectId: 'expense-tracker-app-bb95a',
    storageBucket: 'expense-tracker-app-bb95a.firebasestorage.app',
    iosBundleId: 'com.expancetracker.expanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwgiVTxuXOSoKjiqHsTGTJwkesmpiNaVI',
    appId: '1:987228422764:ios:7322c3ba45bad6c890ce49',
    messagingSenderId: '987228422764',
    projectId: 'expense-tracker-app-bb95a',
    storageBucket: 'expense-tracker-app-bb95a.firebasestorage.app',
    iosBundleId: 'com.expancetracker.expanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRexyMCRZAHfqoHWlOrYUtQUzmwKAhQ0I',
    appId: '1:987228422764:web:61bdb633190805af90ce49',
    messagingSenderId: '987228422764',
    projectId: 'expense-tracker-app-bb95a',
    authDomain: 'expense-tracker-app-bb95a.firebaseapp.com',
    storageBucket: 'expense-tracker-app-bb95a.firebasestorage.app',
    measurementId: 'G-QTL3XNT6ND',
  );
}
